version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - chmod u+x gradlew
      - ./gradlew clean build
artifacts:
  discard-paths: yes
  files:
    - build/libs/restservices.jar